apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: server-deployer-flask-ubuntu
spec:
  finally:
    - name: execute-in-vm
      params:
        - name: vmName
          value: $(tasks.create-vm-from-manifest.results.name)
        - name: secretName
          value: $(tasks.generate-ssh-keys.results.privateKeySecretName)
        - name: script
          value: |
            sudo apt update -y 
            sudo apt install -y git python3-venv pip
            sudo pip install flask
            git clone https://github.com/pallets/flask.git
            echo deploying flaskr...
            pushd flask/examples/tutorial
            export FLASK_APP=flaskr
            flask init-db
            nohup flask run --host=0.0.0.0 > /tmp/server.out 2>&1 &
            echo "deployed, service will listen on port 5000"
      retries: 3
      taskRef:
        kind: ClusterTask
        name: execute-in-vm
      timeout: 1h0m0s
  tasks:
    - name: modify-data-object
      params:
        - name: manifest
          value: |
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              generateName: flasker-server-ubuntu-
              annotations:
                cdi.kubevirt.io/storage.bind.immediate.requested: \"true\"
                cdi.kubevirt.io/storage.deleteAfterCompletion: "false"
            spec:
              pvc:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 5Gi
                volumeMode: Filesystem
              source:
                http:
                  url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
        - name: waitForSuccess
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: modify-data-object
    - name: generate-ssh-keys
      params:
        - name: publicKeySecretName
          value: $(tasks.modify-data-object.results.name)-public-secret
        - name: privateKeySecretName
          value: $(tasks.modify-data-object.results.name)-private-secret
        - name: privateKeyConnectionOptions
          value:
            - 'user:ubuntu'
            - 'disable-strict-host-key-checking:true'
      taskRef:
        kind: ClusterTask
        name: generate-ssh-keys
    - name: create-vm-from-manifest
      params:
        - name: manifest
          value: |
            apiVersion: kubevirt.io/v1alpha3
            kind: VirtualMachine
            metadata:
              generateName: flasker-vm-ubuntu-
              annotation:
                description: ubuntu VM generated by server-deployer-flask-ubuntu pipeline
              labels:
                app: flasker-vm-ubuntu
            spec:
              running: true
              template:
                metadata:
                  labels:
                    kubevirt.io/domain: flasker-vm-ubuntu
                spec:
                  accessCredentials:
                    - sshPublicKey:
                        source:
                          secret:
                            secretName: $(tasks.generate-ssh-keys.results.publicKeySecretName)
                        propagationMethod:
                          configDrive: {}
                  domain:
                    cpu:
                      cores: 2
                    devices:
                      disks:
                        - name: rootdisk
                          bootOrder: 1
                          disk:
                            bus: virtio
                        - name: cloudinitdisk
                          disk:
                            bus: virtio
                      interfaces:
                        - bridge: {}
                          name: default
                      networkInterfaceMultiqueue: true
                      rng: {}
                    resources:
                      requests:
                        memory: 2Gi
                  hostname: flasker-vm-ubuntu
                  networks:
                    - name: default
                      pod: {}
                  volumes:
                    - dataVolume: 
                        name: $(tasks.modify-data-object.results.name)
                      name: rootdisk
                    - name: cloudinitdisk
                      cloudInitConfigDrive:
                        userData: |
                          #cloud-config
                          password: ubuntu
                          chpasswd: { expire: False }
                          runcmd:
                            - useradd -m -s /bin/bash developer
                            - echo "developer:tauhid" | chpasswd
                            - echo "root:root" | chpasswd
                            - echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
      runAfter:
        - generate-ssh-keys
        - modify-data-object
      taskRef:
        kind: ClusterTask
        name: create-vm-from-manifest
