# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    assignees:
      - "ksimon1"
      - "0xFelix"
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "release-v0.16"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    assignees:
      - "ksimon1"
      - "0xFelix"
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "release-v0.15"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    assignees:
      - "ksimon1"
      - "0xFelix"
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "release-v0.13"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    assignees:
      - "ksimon1"
      - "0xFelix"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  
