cat <<EOF > unit-tester-pipelinerun.yaml
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: unit-tester-run-
  labels:
    tekton.dev/pipeline: unit-tester
spec:
  pipelineRef:
    name: unit-tester
  taskRunSpecs:
    - taskServiceAccountName: generate-ssh-keys-task
      pipelineTaskName: generate-ssh-keys
    - taskServiceAccountName: create-vm-from-manifest-task
      pipelineTaskName: create-vm-from-manifest
    - taskServiceAccountName: execute-in-vm-task
      pipelineTaskName: execute-in-vm
    - taskServiceAccountName: cleanup-vm-task
      pipelineTaskName: cleanup-vm
EOF