apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: windows10-installer-run-
spec:
  params:
  - name: winImageDownloadURL
    value: http://185.181.211.5/ISO/Windows_10_PRO_21H2_ENU.iso
  pipelineRef:
    name: windows-bios-installer
  taskRunSpecs:
    - pipelineTaskName: create-source-dv
      taskserviceAccountName: modify-data-object-task
    - pipelineTaskName: create-vm-root-disk
      taskserviceAccountName: modify-data-object-task
    - pipelineTaskName: create-vm
      taskserviceAccountName: create-vm-from-manifest-task
    - pipelineTaskName: wait-for-vmi-status
      taskserviceAccountName: wait-for-vmi-status-task
    - pipelineTaskName: cleanup-vm
      taskserviceAccountName: cleanup-task
status: {}
