---
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: cleanup-vm-with-ssh-taskrun
spec:
  serviceAccountName: cleanup-vm-task
  taskRef:
    kind: Task
    name: cleanup-vm
  params:
    - name: vmName
      value: ${VM-NAME}
    - name: secretName
      value: ${SSH-Secret}
    - name: stop
      value: "true"
    - name: delete
      value: "false"
    - name: timeout
      value: 10m